rethinkdb:
    image: rethinkdb:2.2.4

app:
    build: ./core
    links:
        - rethinkdb
    volumes:
        - /var/www/app/
    ports:
        - "5000:5000"

nginx:
    build: ./nginx
    links:
        - app
    ports:
        - "5050:80"
        - "5051:443"
